### ISSUE TITLE
project review

### ISSUE THREAD

**Issue by sganzfri** [mschoeffler1/ds_portfolio#4]
@masongallo @lemonsoup

Hi Michael,

I looked over your draft presentation slides (Lending Club draft.pdf) and main coding file (LendingClub.ipynb). 

It's possible that the pdf didn't load properly, but assuming it did, I only saw four slides. Either I am missing something, or maybe you were just waiting to finish your experiments to include them. It would be good to include slides with formal descriptions of the data set, techniques, modeling decisions, challenges faced, results, and takeaways/future ideas.

I see that all of this information is spelled out in detail in the ipython notebook, so it's likely you were just waiting to finish up experiments before including them in the presentation.

For the notebook, all of the modeling and data cleaning decisions are described very thoroughly and clearly, and look good.

Given that you are predicting a binary response variable (whether they defaulted or didn't) I agree that logistic regression is a good choice.

It was interesting to see that you determined pretty conclusively that religiosity does in fact have a significant impact on loan repayment. Do you have any intuitive reasons as to why you would expect more religious individuals to be more likely to pay (I think you mentioned some in your presentation, but I don't see that in your slides)? Are there further experiments that can give any more insight? 

It would be helpful to see an additional plot for the final version, that can help visualize the effect of religiosity on loan repayment. I am assuming that, in general, the people from "more religious" areas were more likely to repay? It would be interesting to see a visual depiction.

**Comment by mschoeffler1** [comment]
Sam - 

The slides/notebook are incomplete, but I was happy to get your feedback on their current state.

All religions encourage people to keep their word (and pay back loans). The real question is whether this is just hot air. The stats seem to detect a real, if weak, effect. However, as this is geographic, it only shows that people living in religious areas (who are themselves religious or not) are more likely to repay.

I really need to work on the visualizations. I hope I can pull one that shows what you're asking.

Thank you for the feedback. This will help me build a better final presentation.
