### ISSUE TITLE
Final review

### ISSUE THREAD

**Issue by masongallo** [mschoeffler1/ds_portfolio#6]
Clarity of research problem:

Your research problem is clear. I did not see conclusions or analysis slides at time of review. I am still a little uncomfortable with your research question. I don't think you can really answer the question you've posed about religion given your analysis.

Code:

Your notebook is nicely formatted and clean. I noticed you only use class_weight=None in your notebook. Try tuning this to force the unbalanced dataset issue we discussed in class. 

Next steps:

Mathematically, changing the decision threshold away from 0.5 will only alter your false positives/negatives. In this case, think about the cost of a false pos vs false neg. You will want to balance this likely with the loan amount. Sklearn doesn't have this built in, but we discussed in class the way you can implement this.

**Comment by mschoeffler1** [comment]
Thanks for the detailed comments. I read more deeply on the issue. I may try to build an F2 score (weights more heavily towards recall than F1) and artificially change the threshold as we discussed. 

Data Science For Business (Provost & Fawcett) recommends profit curves (explicitly assigning cost of false positives) or ROC curves when the cost isn't known precisely. The problem domain in their example was similar (fraud detection).

I hope to explore the different options - I've learned a ton from your explanation.

**Comment by masongallo** [comment]
Data Science for Business is an excellent book. Highly recommended, especially for what you're interested in.

**Comment by mschoeffler1** [comment]
Terrific book - and sinking in more deeply this time because of your course. Hoping to solidify my knowledge at the level you're both teaching (initial approaches to the core tools of data science) before tackling the deeper resources you've pointed us to.
